name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    strategy:
      matrix:
        os:
          - ubuntu-latest
        vim_type:
          - vim
        version:
          - head
    runs-on: ${{ matrix.os }}
    steps:
      - name: Setup Vim
        id: vim
        uses: thinca/action-setup-vim@v1
        with:
          vim_type: ${{ matrix.vim_type }}
          vim_version: ${{ matrix.version }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Checkout vim-themis
        uses: actions/checkout@v2
        with:
          repository: thinca/vim-themis
          path: vim-themis
      - name: Run Test
        env:
          THEMIS_VIM: ${{ steps.vim.outputs.executable }}
        run: |
          ./vim-themis/bin/themis
